Using LSB start, seems easier this way

diff --git a/bin/run_server b/bin/run_server
--- a/bin/run_server
+++ b/bin/run_server
@@ -8,33 +8,34 @@
 # WS 20160117
 ############################################################
 
-BASEDIR=/mnt/state
-PREFSDIR=${BASEDIR}/prefs
-LOGDIR=${BASEDIR}/log
-CACHEDIR=${BASEDIR}/cache
-
+if ! . /etc/sysconfig/squeezeboxserver; then
+	echo "Error: Could not read /etc/sysconfig/squeezeboxserver" >&2
+	exit 1
+fi
 
 stopping () {
 echo "Exiting..."
-pkill -f /usr/libexec/squeezeboxserver
+service squeezeboxserver stop
+# pkill -f /usr/libexec/squeezeboxserver
 }
 
 trap 'stopping' 0
 
-if ! grep -sq "$BASEDIR"; then
+if ! mount 2>/dev/null|grep -sq "$BASEDIR"; then
 	echo "State directory is not mounted. Please refer to the readme on how to start this docker image" >&2
 	exit 1
 fi
 
-for DIR in $PREFSDIR $LOGDIR $CACHEDIR; do
+for DIR in $SQUEEZEBOX_CFG_DIR $SQUEEZEBOX_LOG_DIR $SQUEEZEBOX_CACHE_DIR; do
 	if [[ ! -d "$DIR" ]]; then
 		mkdir -p "$DIR"
 	fi
 done
+chown -R ${SQUEEZEBOX_USER}:$SQUEEZEBOX_USER $BASEDIR
 
-exec /usr/libexec/squeezeboxserver --daemon --prefsdir="$PREFSDIR" --logdir="$LOGDIR" --cachedir="$CACHEDIR$" --charset=utf8
+service squeezeboxserver start
 
 # Keep running so we can exit cleanly
 while true; do
-	sleep 5
+	read i
 done
